[package]
name = "snowbank"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = "0.30.1"
anchor-spl  = { version = "0.30.1", features = ["token", "associated_token"] }

[lib]
crate-type = ["cdylib", "lib"]
